[theme]
primaryColor="#0050B3"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#FFFFFF"
textColor="#2E3A59"
font="Segoe UI"
base="light"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false