[theme]
primaryColor="#0050B3"
backgroundColor="#F8FAFC"
secondaryBackgroundColor="#FFFFFF"
textColor="#2E3A59"
font="Segoe UI"

[browser]
gatherUsageStats = false

[server]
enableStaticServing = true
maxUploadSize = 50